openapi: "3.0.0"
info:
  title: API
  version: '0.1'
paths:
  /action:
    post:
      operationId: main.action
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                value_account:
                  type: number
                  format: float
                value_assets:
                  type: number
                  format: float
                price:
                  type: number
                  format: float
                rsi:
                  type: number
                  format: float
      responses:
        200:
          description: action to take (-1 sell, 0 wait, +1 buy)
          content:
            text/plain:
              schema:
                type: integer
        401:
          description: invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidRequest"
components:
  schemas:
    InvalidRequest:
      type: object
      properties:
        error:
          type: string
        details:
          type: string
